README.md
docs/linux-server.md
docs/mail.md
docs/promox.md
docs/reports/2022-02-proxmox-mail-gateway-install.md

documentation on mail gateway installation see #83

documentation on mail gateway

---

README.md
docs/reports/2022-03-03-zammad-elasticsearch-not-running.md
docs/zammad.md

- feat: Setup ElasticSearch for Zammad
- Fixes #91

feat: Setup ElasticSearch for Zammad

---

README.md

- docs: advertise the monitoring repository

docs: advertise the monitoring repository

---

README.md
docs/matomo.md
docs/reports/2021-02-22-matomo-install.md

Porting matomo install docs from #24.

Docs matmoto deploy

---

.github/labeler.yml

ci: Improve labeler

---

.gitignore
README.md
docs/discourse.md
docs/mail.md

Basic documentation for discourse install.

docs: discourse install docs

---

docs/matomo.md

Small doc of matomo site addition

docs: site setup in matomo

---

docs/reports/2022-08-17-openfoodfacts-net-unreachable.md

2022-08-17 stagging was unreachable. Post mortem.

docs: report on openfoodfacts.net unreachable

---

docs/reports/2022-07-kibana-down-es-circuit-breaking-exception.md

reporting while working on https://github.com/openfoodfacts/openfoodfacts-monitoring/issues/55

docs: kibana status problem report

---

README.md
docs/producers_sftp.md
scripts/off1/add_sftp_user.pl
scripts/off1/backup.sh
scripts/off1/crontab-acme-off
scripts/off1/crontab-off
scripts/off1/crontab-root
scripts/off1/lowdiskspace.pl
scripts/off1/lowdiskspace_root.pl
scripts/off1/mdstat.pl
scripts/off2/crontab-off
scripts/off2/crontab-root
scripts/off2/rsync_off1.sh
scripts/off2/zfs-clean.sh
scripts/ovh3/crontab-root
scripts/ovh3/maj-clones-nfs-VM-dockers.sh
scripts/ovh3/snapshot-purge.sh

Document producer sftp setup on off1
And add various scripts from the servers.

docs: document producer sftp and various scripts

---

docs/reports/2022-07-08-journey-to-deploy-off-search.md

Traces on openfoodfacts-search deployment to stagging

docs: report on openfoodfacts-search deploy

---

docs/odoo.md

- Simple updates on module install

docs: update odoo module install

---

.github/workflows/metrics-deploy.yml
docker/metrics/.env
docker/metrics/Makefile
docker/metrics/README.md
docker/metrics/docker-compose.yml
docker/metrics/prod.yml

Add devops code to deploy metrics stack to staging and production.
Create a `deploy-metrics-net` to deploy to staging and `deploy-metrics` to production.

chore: add deployment workflow for metrics stack

---

docs/promox.md

Document how to add disk space on a QEMU VM

docs: adding disk space on a VM

---

README.md

- docs: section about the Monthly meetings

docs: section about the Monthly meetings

---

docs/reports/2022-11-09-monitoring-move-to-own-vm.md

Report on moving monitoring dockers from staging VM to their own VM.
Fixes: 
- #89

docs: Monitoring move

---

scripts/off2/crontab-off
scripts/off2/crontab-root
scripts/off2/rsync_off1.sh
scripts/off2/sync2ovh3.sh

part of:
- #180
I think we should even change it another time and run it to run in root crontab.
We would still connect to ovh3 with raphael0202 account.

fix: fix rsync script

---

scripts/off1/sto-products-sync.sh
scripts/ovh3/nginx-conf/static-off

I saw things that were not saved and used in prod:
- nginx config for images on OVH3
- off1 zfs sync

docs: add scripts used in prod

---

README.md
docs/mongodb.md
scripts/off2/crontab-root

Documenting MongoDB and how I put logrotate

docs: page on mongodb and logrotate

---

docs/discourse.md

docs: Matomo setup on forum

---

docs/reports/2023-03-14-off2-opff-reinstall.md
docs/sanoid.md
docs/zfs-overview.md

A file to explain sanoid.
and some additions to opff install.

docs: documenting sanoid

---

.github/ISSUE_TEMPLATE/bug_report.md

fix: Update bug_report.md

---

docs/reports/2023-06-08-stalled-zfs-sync-off-products.md
scripts/off1/sto-products-sync.sh

Problem of sync on ovh3, with a blocking situation.

fix: fixing lost sync of off products on ovh3

---

scripts/mirabelle/distri-qual.sh

chore: Fix a small typo (mirabelle/distri-qual.sh)

---

docs/logs-ovh3.md
docs/reports/2023-07-16-ovh3-sdc-broken.md

sdc was in error on ovh3 and we had to replace it.

docs: report on ovh3 disk replace

---

scripts/off1/sto-products-sync.sh

changed policy for old snapshot removal

chore: update sto-product-sync as is on off1

---

docs/logs-off2.md
docs/nginx-reverse-proxy.md
docs/reports/2024-01-19-certbot-failure-off2-proxy

docs: certbot failures on off2 reverse proxy

---

docs/reports/2024-02-06-cleanup-products-snapshots.md

I did some cleanups of snapshot (remaining from the old snapshot system).

docs: cleanup of products snapshots on off2

---

scripts/utils/logs/anonymize_logs.pl

This will enable keeping nginx logs in a GDPR compliant way.

feat: log anonymizer

---

docs/disks.md
docs/reports/2023-11-28-ovh3-sdf-broken.md
docs/zfs-overview.md

Document past incident as it is useful experience.

docs: ovh3 broken disks

---

docs/redis.md
docs/reports/2024-01-04-setting-up-stunnel.md
docs/stunnel.md

Add some precisions after discussing the matter with Alex.
@alexgarel feel free to update it as you like if needed.

docs: improve documentation about stunnel and redis

---

docs/observability.md
docs/reports/2024-02-20-exporter-on-mongodb-ct.md

exposing prometheus exporters through nginx proxy

docs: free exporters

---

confs/off-redis/redis/redis.conf
docs/reports/2024-02-28-upgrade-redis.md

I performed the upgrade to v7 of redis, the new config file (and report) are available here.

chore: switch redis config to 7.2.4

---

confs/gdrive-backup/rclone-drives-config
confs/gdrive-backup/systemd/system/email-failures@.service
confs/gdrive-backup/systemd/system/rclone_backup@.service
confs/gdrive-backup/systemd/system/rclone_backup@.timer
docs/rclone.md
docs/reports/2023-11-28-google-drive-backup-setup.md

Setting up a container with rclone to backup our google drive.

docs: google drive backup

---

docker/argilla/docker-compose.yml

deployed at https://argilla.openfoodfacts.org

feat: add argilla docker-compose.yml

---

docs/mail.md
docs/reports/2024-04-18-setup-dkim-google-workspace.md

docs: gmail dkim setup

---

docs/cicd.md
docs/proxmox.md
docs/reports/2024-04-12-install-off-query-off1.md

We need space on ovh2… we got to move off-query to off1 (~ 170Gb).

docs: moving off-query to off1

---

docs/reports/2022-09-23-odoo-setup-for-pro-platform.md

Logs of what I will do to setup odoo for producers platform

docs: odoo setup for producers platform

---

README.md

- docs: Update README.md by adding status page

docs: Update README.md by adding status page

---

docs/reports/2024-08-07-wordpress-off-contents-fresh-install.md

What I did to have a fresh wordpress install for the open food facts contents.

docs: fresh wordpress install for OFF contents

---

confs/moji-stunnel-client/stunnel/off.conf
confs/moji-stunnel-server/stunnel/off.conf
confs/ovh-stunnel-client/stunnel/off.conf

Add stunnel configuration for Moji server (CT stunnel-client and stunnel-server).

chore: add stunnel configurations

---

docs/moji-datacenter.md
docs/nginx-reverse-proxy.md
docs/reports/2024-08-13-moji-server-installation.md

Add report about moji server setup.

docs: add report about moji server installation
